openapi: 3.0.1
info:
  title: Summarizer Plugin
  description: Plugin for summarizing tv scripts and extract entities.
  version: 'v1'
servers:
  - url: https://summarizer-plugin.onrender.com
paths:
  /summarize:
    post:
      operationId: summarizeScript
      summary: Summarize a script
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/summarizeScriptRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/summaryResponse'

components:
  schemas:
    summarizeScriptRequest:
      type: object
      required:
      - script
      properties:
        script:
          type: string
          description: The script to be summarized
          required: true
    
    summaryResponse:
      type: object
      properties:
        summary:
          type: string
        entities:
          type: array
          items:
            type: string
           